
# Custom dictionary for short forms and slang
unsorted_slang_dict = {
    'lol': 'laugh out loud',
    'rofl': 'rolling on the floor laughing',
    'lmao': 'laughing my ass off',
    'idk': 'i don\'t know',
    'idc': 'i don\'t care',
    'yolo': 'you only live once',
    'tbh': 'to be honest',
    'imo': 'in my opinion',
    'fyi': 'for your information',
    'brb': 'be right back',
    'afk': 'away from keyboard',
    'ty': 'thank you',
    'thx': 'thanks',
    'gr8': 'great',
    "gud": "good",
    "osm": "awesome",
    "gr8": "great",
    "u": "you",
    "ur": "your",
    "btw": "by the way",
    "thx": "thanks",
    "plz": "please",
    'b4': 'before',
    'cuz': 'because',
    'bc': 'because',
    'u': 'you',
    'r': 'are',
    'y': 'why',
    'k': 'okay',
    'sup': 'what\'s up',
    'wbu': 'what about you',
    'gonna': 'going to',
    'wanna': 'want to',
    'tho': 'though',
    'lit': 'exciting',
    'af': 'as fuck',
    'rn': 'right now',
    'wtf': 'what the fuck',
    'wth': 'what the hell',
    'omg': 'oh my god',
    'smh': 'shaking my head',
    # Add more short forms and slang as needed
}
sorted_keys = sorted(unsorted_slang_dict.keys())
slang_dict = {key: unsorted_slang_dict[key] for key in sorted_keys}
